In [5]:
import time

import torch.optim as optim
from tqdm import tqdm

from args import get_args
from utils import *
import torch
import model.ts_flows as fnn
import numpy as np

# device = "cuda"
device = "cpu"

In [235]:

'''===========flow============'''
act = 'tanh'
num_blocks = 10
flow = fnn.MAF( n_blocks=num_blocks, input_size=3, hidden_size=3, n_hidden=4 )
# flow = fnn.FlowSequential(flow)
flow.to(device)
optimizer = optim.Adam(flow.parameters(), lr=0.01, weight_decay=1e-6)

In [236]:
optimizer.zero_grad()
epoch = 100
for i in range(epoch):
    x = torch.tensor([[[1.0,2,3],[4,5,6]]]) # [1, 2, 3]
    cond = torch.tensor([[[1.0,1,1],[2,2,2]]])
    cond = None
    
    loss = flow.log_prob(x, cond)
    loss = -loss.mean()
    loss.backward()
    print(loss)
    optimizer.step()

tensor(5.7605, grad_fn=<NegBackward0>)
tensor(5.7437, grad_fn=<NegBackward0>)
tensor(5.7271, grad_fn=<NegBackward0>)
tensor(5.7100, grad_fn=<NegBackward0>)
tensor(5.6928, grad_fn=<NegBackward0>)
tensor(5.6748, grad_fn=<NegBackward0>)
tensor(5.6555, grad_fn=<NegBackward0>)
tensor(5.6348, grad_fn=<NegBackward0>)
tensor(5.6119, grad_fn=<NegBackward0>)
tensor(5.5868, grad_fn=<NegBackward0>)
tensor(5.5588, grad_fn=<NegBackward0>)
tensor(5.5292, grad_fn=<NegBackward0>)
tensor(5.4912, grad_fn=<NegBackward0>)
tensor(5.4497, grad_fn=<NegBackward0>)
tensor(5.4019, grad_fn=<NegBackward0>)
tensor(5.3457, grad_fn=<NegBackward0>)
tensor(5.2928, grad_fn=<NegBackward0>)
tensor(5.2304, grad_fn=<NegBackward0>)
tensor(5.1523, grad_fn=<NegBackward0>)
tensor(5.0736, grad_fn=<NegBackward0>)
tensor(4.9495, grad_fn=<NegBackward0>)
tensor(4.7714, grad_fn=<NegBackward0>)
tensor(4.5544, grad_fn=<NegBackward0>)
tensor(4.2408, grad_fn=<NegBackward0>)
tensor(3.7110, grad_fn=<NegBackward0>)
tensor(2.6616, grad_fn=<N

In [237]:
u, _ = flow.forward(x, cond)
u

tensor([[[-0.8866, -0.8866, -0.8866],
         [ 0.8866,  0.8866,  0.8866]]], grad_fn=<AddBackward0>)

In [255]:
flow.sample(x.shape[:-1])

tensor([[[4.8813, 2.5117, 4.5217],
         [2.1894, 2.4045, 6.8735]]], grad_fn=<CopySlices>)

In [256]:
y,_ = flow.inverse(u, cond)
y

tensor([[[1.0000, 2.0000, 3.0000],
         [4.0000, 5.0000, 6.0000]]], grad_fn=<CopySlices>)

In [187]:
o = torch.tensor([[1,2,3]])
y,_ = flow.inverse(o, cond)
y

tensor([[ 4.4100,  7.3647, 10.3172]], grad_fn=<CopySlices>)

torch.distributions.Normal 的使用

In [161]:
from torch.distributions import Normal
nom = Normal(torch.tensor([0.0,0,0]), torch.tensor([1.0,1,1]))


In [267]:
nom.sample([1,2])

tensor([[[-1.4506,  1.7755, -0.2086],
         [ 1.2143, -1.2006, -1.7235]]])